In [25]:
import numpy as np
import pygame, sys, random

## drawing game board
- 22,10 matrix of strings

In [26]:
class Tetrion:
    "game boards"
    
    def __init__(self,name,size):
        """initialize game_matrix spaces"""
        self.name = name
        self.size = size
        self.board = None
        self.default_board()
        
    def default_board(self, default_fill = ''):
        """self.board is reassigned to matrix(size)"""
        if self.board == None:
            self.board = np.full(shape=self.size, fill_value=default_fill, dtype=object)
            return(self.board)
    

    def full_row(self,default_fill = '',empty=False): 
        """returns row index of full () rows""" 
        list_index=[]
        
        #default
        if empty == False:
            for i,j in enumerate(self.board):
                # check rows to see if all row-elements arent empty
                if np.all(j != default_fill):
                    list_index.append(i)
                    #print("row {} full".format(i))
                #else: print("row {} clear".format(i))
        
        #used for row_roll
        elif empty == True: 
            for i,j in enumerate(self.board):
                if np.all(j == default_fill):
                    list_index.append(i)
        return(list_index)
        
    def empty_full_row(self,default_fill = ''):
        """clears rows indicated by full_row()"""
        row_list = self.full_row()
        
        for i,j in enumerate(self.board):
            for k in row_list:
                if i == k:
                    #print("clearing row {}".format(i))
                    self.board[i] = default_fill
                    row_list.remove(i)
        #return(self.board)

                    
    def row_roll(self):
        """shifts unempty rows downwards if there's empty rows bow"""
        # np.roll loops through board[0:empty_index] -> empty row to top
        
        roll_list = self.full_row(empty=True)
        #print(roll_list) 
        for i in roll_list:
            print('rolling [0:{}]'.format(i))
            self.board[0:i+1]=np.roll(self.board[0:i+1],shift=1,axis=0)
        return(self.board)

In [27]:
spawn_area = Tetrion(name='spawn',size=(2,10))
play_area= Tetrion(name='play',size=(20,10))
on_deck = Tetrion(name='next_piece', size=(2,4))

In [28]:
play_area.board[15] = 0
play_area.board[16][3] = 2
play_area.board[17][0:3] = 2
play_area.board[18] = 0
play_area.board[0][4:9] = 2
play_area.board[19][0:9] = 2

play_area.board[5][1:9] = 2
play_area.board[6][0:] = 1
play_area.board[7][9] = 0
play_area.board

array([['', '', '', '', 2, 2, 2, 2, 2, ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', 2, 2, 2, 2, 2, 2, 2, 2, ''],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       ['', '', '', '', '', '', '', '', '', 0],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       ['', '', '', 2, '', '', '', '', '', ''],
       [2, 2, 2, '', '', '', '', '', '', ''],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, '']], dtype=object)

In [34]:
play_area.full_row()
play_area.empty_full_row()
play_area.row_roll()

rolling [0:0]
rolling [0:1]
rolling [0:2]
rolling [0:3]
rolling [0:4]
rolling [0:5]
rolling [0:6]
rolling [0:7]
rolling [0:8]
rolling [0:9]
rolling [0:10]
rolling [0:11]
rolling [0:12]
rolling [0:13]


array([['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', 2, 2, 2, 2, 2, ''],
       ['', 2, 2, 2, 2, 2, 2, 2, 2, ''],
       ['', '', '', '', '', '', '', '', '', 0],
       ['', '', '', 2, '', '', '', '', '', ''],
       [2, 2, 2, '', '', '', '', '', '', ''],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, '']], dtype=object)

In [32]:
def lock_in():
    """locks a piece in position"""
    pass

In [78]:
spawn_area.board[: , 3:7] =0
spawn_area.board

array([['', '', '', 0, 0, 0, 0, '', '', ''],
       ['', '', '', 0, 0, 0, 0, '', '', '']], dtype=object)

In [133]:
spawn_area.board[:]= ''

In [211]:
# uses spawn_area from Tetrion and T_block from Tetronimoe
def spawn_piece(T_block, default_fill='', color=False):
    """"assign T_block to spawn (middle columns)"""
    
    # ensure no other block is in spawn
    if np.any(spawn_area.board[:] != default_fill):
        spawn_area.board[:]= default_fill
       
    #block_length = len(T_block[0]) #amount of columns
    block_length = T_block.len
    end_column = 3 + block_length
    
    #colored return
    if color == True:
        fill_t = T_block.color_matrix()
    else:
        fill_t = T_block.size
    
    #return spawn
    if block_length == 4: # I piece
        spawn_area.board[1: , 3:end_column] = fill_t
    else: # all other pieces 
        spawn_area.board[: , 3:end_column] = fill_t
 
    return(spawn_area.board)


# breaks on rotation, need to lock rotation while in spawn
# redundancies ~~~ 


In [215]:
spawn_piece(L) 


array([['', '', '', 0, 0, 1, '', '', '', ''],
       ['', '', '', 1, 1, 1, '', '', '', '']], dtype=object)

In [234]:
spawn_piece(I,color=True) 

ValueError: could not broadcast input array from shape (4,1) into shape (1,4)

In [233]:
I.rotate_block('up')
#breaks spawn

array([[1],
       [1],
       [1],
       [1]])

______

## Pieces
- class (name, color, size)
    - rotation

In [227]:
class Tetronimoe:
    """ Tetris block operations """
    def __init__(self, name, size, color):
        """self.size is an identity matrix for the block"""
        self.name = name
        self.size = size
        self.color = color
        self.len = len(self.size[0])
        
        self.default_size = None
        self.default()
        
    def default(self):
        """initial state of block size is stored"""
        if self.default_size == None:
            self.default_size = self.size
        return(self.default_size)
        
    def color_matrix(self):
        """returns a string matrix of the colored piece"""
        return(np.where(self.size == 0, '', self.color))
    
    def rotate_block(self, rotation_direction,color=False):
        """block orientation is reassigned with rotation"""
        #clockwise
        if rotation_direction == 'up':
            self.size = np.rot90(self.size, k=-1, axes=(0,1))
            
        #counter-clockwise
        elif rotation_direction == 'down':
            self.size = np.rot90(self.size, k=1, axes=(0,1))
        
        # returns identity or color matrix
        if color == False: 
            return(self.size)
        elif color == True:
            return(self.color_matrix())


In [228]:
#changed I.size to a one dimension matrix
I = Tetronimoe('I_block', color = 'cyan', size = np.array([[1,1,1,1]]) )
J = Tetronimoe('J_block', color = 'purple', size = np.array([[1,0,0],[1,1,1]]) )
L = Tetronimoe('L_block', color = 'orange', size = np.array([[0,0,1],[1,1,1]]) )
O = Tetronimoe('O_block', color = 'yellow', size = np.array([[1,1],[1,1]]) )
S = Tetronimoe('S_block', color = 'green', size = np.array([[0,1,1],[1,1,0]]) )
Z = Tetronimoe('Z_block', color = 'red', size = np.array([[1,1,0],[0,1,1]]) )
T = Tetronimoe('T_block', color = 'purple', size = np.array([[0,1,0],[1,1,1]]) )

In [229]:
I.color_matrix()

array([['cyan', 'cyan', 'cyan', 'cyan']], dtype='<U4')

In [230]:
I.rotate_block('up',color=True)

array([['cyan'],
       ['cyan'],
       ['cyan'],
       ['cyan']], dtype='<U4')

In [231]:
I.rotate_block('down')

array([[1, 1, 1, 1]])

In [226]:
I.default_size

array([[1, 1, 1, 1]])

In [225]:
I.rotate_block("up")

array([[1],
       [1],
       [1],
       [1]])

## weighted tetronimoe/piece randomizer
- 7 pieces in a bag of 35 total; 5 of each piece
    - https://tetris.wiki/TGM_randomizer 
    - https://tetris.wiki/Random_Generator
    

In [605]:
T_blocks = (I, J, L, T, O, S, Z) #tetronimoe class objects
def heavy_bag(start=False):
    """returns name values of tetronimoes for randomizer use"""
    all_blocks = [i.name for i in T_blocks]
    
    # first block spawn != (S,Z,O)
    if start == True: 
        start_blocks = [i.name for i in T_blocks[0:4]]
        return(start_blocks)
    
    
    else: return(all_blocks)
heavy_bag()

['I_block', 'J_block', 'L_block', 'T_block', 'O_block', 'S_block', 'Z_block']

In [606]:
heavy_bag(True) #starting block

['I_block', 'J_block', 'L_block', 'T_block']

In [587]:
START = random.choice(heavy_bag(True)*7) # starting block legal; != (S,Z,O)
full_bag = heavy_bag()*7

In [588]:
def random_next(first):
    """randomizor tries 6 times for no duplicate pieces in a row"""
    x=6 
    
    second = random.choice(full_bag)
    
    while second == first:
        #print("duplicate: {}".format(second))
        second = random.choice(full_bag)
        #print("second is now {}".format(second))
        x -= 1
        #print("{} attempts left".format(x))
        if second != first or x == 0:
            break
    #print("{} != {}".format(first,second))
    return(second)

In [589]:
#starting bag:
## START = random.choice(heavy_bag(True)*7)

def make_bag(starting_block=None,bag_size=6):
    """makes a bag of tetronimoe pieces using random_next function """
    
    #
    piece_list=[starting_block]
    
    for i in range(bag_size-1): 
        piece_list.append(random_next(piece_list[i]))
    return(piece_list)

In [590]:
full_bag = heavy_bag()*7


In [682]:
# first check if all 7 pieces were used in pool
# pieces not in second pool are added to randomizer 
# full_bag = heavy_bag()*7
# previous_pool is a 6 item name list
# BLOCKS = heavy_bag() returns a list of the block names

def adjust_weight(previous_pool, weighted_bag=full_bag):
    """modifies the total pool for pieces to randomize from"""
    return_weight = weighted_bag
    BLOCKS = heavy_bag()
    for i in BLOCKS:
        if i in previous_pool and i in return_weight:
            #print('removing {} from next bag'.format(i))
            return_weight.remove(i)
        
        elif i not in previous_pool:
            #print('adding {} to next bag'.format(i))
            return_weight.append(i)
            
    #print(len(return_weight))
    return(return_weight)

In [683]:

def random_next_weighted(first,WEIGHT_BAG=full_bag):
    #################### WEIGHTED #############
    x=6 
    
    second = random.choice(WEIGHT_BAG)
    
    while second == first:
        #print("duplicate: {}".format(second))
        second = random.choice(WEIGHT_BAG)
        #print("second is now {}".format(second))
        x -= 1
        #print("{} attempts left".format(x))
        if second != first or x == 0:
            break
    #print("{} != {}".format(first,second))
    return(second)


In [732]:
#want to modify make_bag so it applies random_next to all previous pieces 
### NOT WORKING AS INTENDED BUT WORKING
#check all previous? then 
def make_bag_copy(starting_block):
    ### 
    
    piece_list=[starting_block] # initially a list of 1 item
    
    for i in range(5): 
        x = random_next_weighted(piece_list[i])
        y = random_next_weighted(piece_list[i])
        for j in piece_list:
            if x == j:
                x = y
        piece_list.append(x)
                
    return(piece_list)

#make_bag_copy(START)

In [733]:
st_bag = make_bag_copy(START)
#print(st_bag)
pool_b1 = adjust_weight(st_bag)

In [734]:
bag2 = make_bag_copy(starting_block=random_next_weighted(st_bag[-1],pool_b1))
pool_b2 = adjust_weight(bag2)

In [735]:
bag3 = make_bag_copy(starting_block=random_next_weighted(bag2[-1],pool_b2))
pool_b3 = adjust_weight(bag3)

In [736]:
full_bag = heavy_bag()*7

In [737]:

def return_bag(BAG_LIST=None,BAG_POOL=None,START=False):
    """returns a 6 block pool followed by the remaining weighted pool"""
    # BAG_LIST --> generated list of *randomized blocks
    # BAG_POOL --> generated weighted pool
    # assigned None because start
    
    if START == True:  
        #single element list to start out with
        starting_choice = random.choice(heavy_bag(True)*7)
        
        # creates a list of elements following ^
        b_list = make_bag_copy(starting_choice)
        
        # adjusts weight of random pool
        pool_b = adjust_weight(b_list, weighted_bag=full_bag)
        #START == False
        #return(b_list,pool_b)
    
    else:
        # random_next_weighted() -> last element of the previous list -> generate next start
        pool_previous = random_next_weighted(BAG_LIST[-1],BAG_POOL)
        
        # generate list using ^
        b_list = make_bag_copy(starting_block=pool_previous)
        
        #adjust weight of random pool
        pool_b = adjust_weight(previous_pool = b_list, weighted_bag = BAG_POOL)
    return(b_list,pool_b)

In [765]:
a = return_bag(BAG_LIST=None,BAG_POOL=None,START=True)
b=return_bag(a[0],a[1],START=False)
c=return_bag(b[0],b[1],START=False)

In [766]:
print(a[0],a[1])
print(len(a[1]))

print(b[0],b[1])
print(len(b[1]))

print(c[0],c[1])
print(len(c[1]))

['L_block', 'T_block', 'S_block', 'O_block', 'Z_block', 'S_block'] ['J_block', 'J_block', 'J_block', 'I_block', 'J_block', 'I_block', 'J_block', 'I_block', 'I_block', 'J_block', 'I_block', 'J_block', 'I_block', 'J_block', 'J_block', 'I_block', 'J_block', 'I_block', 'J_block', 'J_block', 'I_block', 'J_block', 'J_block', 'L_block', 'J_block']
25
['I_block', 'S_block', 'Z_block', 'O_block', 'S_block', 'T_block'] ['J_block', 'J_block', 'J_block', 'I_block', 'J_block', 'I_block', 'J_block', 'I_block', 'I_block', 'J_block', 'I_block', 'J_block', 'I_block', 'J_block', 'J_block', 'I_block', 'J_block', 'I_block', 'J_block', 'J_block', 'I_block', 'J_block', 'J_block', 'L_block', 'J_block']
25
['I_block', 'L_block', 'Z_block', 'S_block', 'T_block', 'O_block'] ['J_block', 'J_block', 'J_block', 'I_block', 'J_block', 'I_block', 'J_block', 'I_block', 'I_block', 'J_block', 'I_block', 'J_block', 'I_block', 'J_block', 'J_block', 'I_block', 'J_block', 'I_block', 'J_block', 'J_block', 'I_block', 'J_block'

In [745]:
d=return_bag(c[0],c[1])

In [744]:
len(c[1])

39

In [797]:
# return a sequence of lists generated by return_bag()
# return_bag weight resets if len(pool_b) is less than threshold
def return_bag_out():
    
    start = return_bag(START=True) #tuple
    s=[]
    next_iter = return_bag(start[0],start[1])
    print(next_iter[0],len(next_iter[1]))
return_bag_out()

['I_block', 'Z_block', 'L_block', 'S_block', 'Z_block', 'L_block'] 56
(['J_block', 'L_block', 'O_block', 'S_block', 'T_block', 'Z_block'], ['J_block', 'J_block', 'I_block', 'J_block', 'I_block', 'J_block', 'J_block', 'J_block', 'J_block', 'I_block', 'J_block', 'J_block', 'J_block', 'I_block', 'I_block', 'J_block', 'J_block', 'I_block', 'J_block', 'I_block', 'I_block', 'J_block', 'J_block', 'I_block', 'I_block', 'I_block', 'J_block', 'I_block', 'J_block', 'I_block', 'J_block', 'J_block', 'I_block', 'J_block', 'I_block', 'I_block', 'J_block', 'I_block', 'J_block', 'J_block', 'I_block', 'J_block', 'I_block', 'J_block', 'J_block', 'I_block', 'J_block', 'J_block', 'I_block', 'I_block', 'I_block', 'J_block', 'I_block', 'J_block', 'T_block', 'O_block'])


In [758]:
for i,j in enumerate(range(3)):
    
    print(i,j)
    

0 0
1 1
2 2
